# Generated by Django 3.2.5 on 2021-10-19 12:46

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def migrate_phone_numbers(apps, schema_editor):
    User = apps.get_model("accounts", "CustomUser")
    Person = apps.get_model("people", "Person")
    deleted_phone_numbers = 0
    for user in User.objects.all():
        try:
            person = Person.objects.get(user=user)
            person.phone_number = user.phone_number
            person.save()
        except ObjectDoesNotExist:
            deleted_phone_numbers += 1
    print(f"Phone numbers deleted: {deleted_phone_numbers}")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("people", "0013_person_phone_number"),
    ]

    operations = [
        migrations.RunPython(migrate_phone_numbers),
    ]
